server:
  port: 8080

spring:
  application:
    name: TelegramBot


chat:
  message: D:/WorkSpaceIdea/TelegramBot/templete/message.csv
  channalMessage: D:/WorkSpaceIdea/TelegramBot/templete/onetomany.csv
  welcomeText: D:/WorkSpaceIdea/TelegramBot/templete/welcome.txt
msgbot:
  token:
  name:
proxy:
  enable: false
  host: 127.0.0.1
  port: 8889
  user:
  password:

ownthink:
  enable: false
  appid:
  userid:
